In [2]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:123@localhost:5432/dreamhomes")

def run(title, sql):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print('='*60)
    with engine.connect() as c:
        df = pd.read_sql(sql, c)
    print(df.to_string(index=False))
    return df

In [3]:
# ── Q1: Average sale price by borough ──────────

run("Q1: Avg Sale Price by Borough", """
    SELECT b.borough_name,
           ROUND(AVG(st.sale_price)) AS avg_sale_price,
           COUNT(*) AS num_sales
    FROM borough b
    JOIN property p ON p.borough_id = b.borough_id
    JOIN sales_transaction st ON st.property_id = p.property_id
    GROUP BY b.borough_name
    ORDER BY avg_sale_price DESC
""")

============================================================
  Q1: Avg Sale Price vs Violations by Borough
============================================================
 borough_name  avg_sale_price  num_sales
    MANHATTAN       2855743.0      12360
     BROOKLYN       1495929.0      11560
        BRONX       1055673.0       3564
       QUEENS        827904.0      13679
STATEN ISLAND        786944.0       4022
  CONNECTICUT        266406.0      59068

    borough_name  avg_sale_price  num_sales
0      MANHATTAN       2855743.0      12360
1       BROOKLYN       1495929.0      11560
2          BRONX       1055673.0       3564
3         QUEENS        827904.0      13679
4  STATEN ISLAND        786944.0       4022
5    CONNECTICUT        266406.0      59068

In [4]:
# ── Q2: Top 10 zip codes by quality score ─────────────────────────
run("Q2: Top 10 Zip Codes by Quality Score", """
    SELECT zip_code,
           ROUND(quality_score::numeric, 1) AS quality_score,
           ROUND(median_sale_price) AS median_sale_price,
           violation_count, complaint_count
    FROM neighborhood_quality_score
    ORDER BY quality_score DESC
    LIMIT 10
""")

============================================================
  Q2: Top 10 Zip Codes by Quality Score
============================================================
zip_code  quality_score  median_sale_price  violation_count  complaint_count
   10015          100.0          1302486.0                0                0
   11695          100.0           766948.0                0                0
   11005          100.0           575611.0                0                0
   11109          100.0           959333.0                0                0
   10282           99.9          1818106.0                0                1
   10005           99.8          1463775.0                0                2
   11040           99.8           699075.0                0                2
   11697           99.8           490929.0                0                2
   11001           99.4           856846.0                1                1
   11362           99.0           788597.0                1                5

  zip_code  quality_score  median_sale_price  violation_count  complaint_count
0    10015          100.0          1302486.0                0                0
1    11695          100.0           766948.0                0                0
2    11005          100.0           575611.0                0                0
3    11109          100.0           959333.0                0                0
4    10282           99.9          1818106.0                0                1
5    10005           99.8          1463775.0                0                2
6    11040           99.8           699075.0                0                2
7    11697           99.8           490929.0                0                2
8    11001           99.4           856846.0                1                1
9    11362           99.0           788597.0                1                5

In [5]:

# ── Q3: CT towns with highest % sold below assessment ─────────────
run("Q3: CT Towns — % Sold Below Assessment", """
    SELECT m.town_name,
           COUNT(*) AS total_sales,
           SUM(CASE WHEN st.sold_below_assessment THEN 1 ELSE 0 END) AS below_assessment,
           ROUND(100.0 * SUM(CASE WHEN st.sold_below_assessment THEN 1 ELSE 0 END)
                 / COUNT(*), 2) AS pct_below
    FROM municipality m
    JOIN property p ON p.municipality_id = m.municipality_id
    JOIN sales_transaction st ON st.property_id = p.property_id
    WHERE p.region = 'CT'
    GROUP BY m.town_name
    HAVING COUNT(*) > 10
    ORDER BY pct_below DESC
    LIMIT 15
""")

============================================================
  Q3: CT Towns — % Sold Below Assessment
============================================================
 town_name  total_sales  below_assessment  pct_below
      Kent           51                26      50.98
Washington           21                 9      42.86
    Sharon           12                 5      41.67
 Southbury         1177               427      36.28
Bridgeport         1819               639      35.13
  Sterling           29                 8      27.59
Torrington          586               153      26.11
  Griswold           62                16      25.81
 Naugatuck          438               103      23.52
    Berlin          468               108      23.08
  Woodbury          236                48      20.34
 Woodstock           64                13      20.31
   Redding           25                 5      20.00
    Bethel          476                95      19.96
New London          275                54      19.64

     town_name  total_sales  below_assessment  pct_below
0         Kent           51                26      50.98
1   Washington           21                 9      42.86
2       Sharon           12                 5      41.67
3    Southbury         1177               427      36.28
4   Bridgeport         1819               639      35.13
5     Sterling           29                 8      27.59
6   Torrington          586               153      26.11
7     Griswold           62                16      25.81
8    Naugatuck          438               103      23.52
9       Berlin          468               108      23.08
10    Woodbury          236                48      20.34
11   Woodstock           64                13      20.31
12     Redding           25                 5      20.00
13      Bethel          476                95      19.96
14  New London          275                54      19.64

In [6]:
# ── Q4: School attendance rate vs avg sale price by district ──────
run("Q4: School Attendance Rate vs Avg Sale Price", """
    WITH district_stats AS (
        SELECT sd.district_id, b.borough_name,
               AVG(s.attendance_rate) AS avg_attendance,
               AVG(st.sale_price)     AS avg_price
        FROM school_district sd
        JOIN borough b ON b.borough_id = sd.borough_id
        JOIN school s ON s.district_id = sd.district_id
        JOIN property_school ps ON ps.dbn = s.dbn
        JOIN property p ON p.property_id = ps.property_id
        JOIN sales_transaction st ON st.property_id = p.property_id
        GROUP BY sd.district_id, b.borough_name
    )
    SELECT borough_name,
           ROUND(avg_attendance::numeric, 2) AS avg_attendance_rate,
           ROUND(avg_price) AS avg_sale_price,
           CASE WHEN avg_attendance > 0.9 THEN 'High' ELSE 'Low' END AS tier
    FROM district_stats
    ORDER BY avg_attendance DESC
""")

============================================================
  Q4: School Attendance Rate vs Avg Sale Price
============================================================
borough_name  avg_attendance_rate  avg_sale_price tier
   MANHATTAN                 0.96       1379194.0 High
   MANHATTAN                 0.92       1379194.0 High
   MANHATTAN                 0.91       1379194.0 High
   MANHATTAN                 0.91       1391771.0 High
   MANHATTAN                 0.89       1384283.0  Low
   MANHATTAN                 0.83       1391771.0  Low

  borough_name  avg_attendance_rate  avg_sale_price  tier
0    MANHATTAN                 0.96       1379194.0  High
1    MANHATTAN                 0.92       1379194.0  High
2    MANHATTAN                 0.91       1379194.0  High
3    MANHATTAN                 0.91       1391771.0  High
4    MANHATTAN                 0.89       1384283.0   Low
5    MANHATTAN                 0.83       1391771.0   Low

In [7]:
# ── Q5: Top 311 complaint types in high-complaint zip codes ───────
run("Q5: Top 311 Complaint Types by Zip Code", """
    SELECT zip_code, complaint_type, COUNT(*) AS cnt,
           ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY zip_code), 1) AS pct
    FROM service_request_311
    WHERE zip_code IS NOT NULL
    GROUP BY zip_code, complaint_type
    HAVING COUNT(*) > 100
    ORDER BY zip_code, cnt DESC
    LIMIT 30
""")

============================================================
  Q5: Top 311 Complaint Types by Zip Code
============================================================
zip_code complaint_type  cnt   pct
   10002 HEAT/HOT WATER  246 100.0
   10003 HEAT/HOT WATER  285 100.0
   10009 HEAT/HOT WATER  408 100.0
   10011 HEAT/HOT WATER  194 100.0
   10014 HEAT/HOT WATER  194 100.0
   10016 HEAT/HOT WATER  107 100.0
   10019 HEAT/HOT WATER  180 100.0
   10023 HEAT/HOT WATER  150 100.0
   10024 HEAT/HOT WATER  255 100.0
   10025 HEAT/HOT WATER  557 100.0
   10026 HEAT/HOT WATER  634 100.0
   10027 HEAT/HOT WATER  666 100.0
   10028 HEAT/HOT WATER  132 100.0
   10029 HEAT/HOT WATER  588 100.0
   10030 HEAT/HOT WATER  618 100.0
   10031 HEAT/HOT WATER 1059 100.0
   10032 HEAT/HOT WATER  986 100.0
   10033 HEAT/HOT WATER  806 100.0
   10034 HEAT/HOT WATER  671 100.0
   10035 HEAT/HOT WATER  368 100.0
   10036 HEAT/HOT WATER  121 100.0
   10037 HEAT/HOT WATER  347 100.0
   10039 HEAT/HOT WATER  680 100.0
   10040 HEAT/HOT WATER  755 100.0
   10128 HEAT/HOT WATER  138 100.0
   10301 HEAT/HOT WATER  161 100.0
   10451 HEAT/HOT WATER  817 100.0
   10452 HEAT/HOT WATER 1382 100.0
   10453 HEAT/HOT WATER 1245 100.0
   10454 HEAT/HOT WATER  312 100.0

   zip_code  complaint_type   cnt    pct
0     10002  HEAT/HOT WATER   246  100.0
1     10003  HEAT/HOT WATER   285  100.0
2     10009  HEAT/HOT WATER   408  100.0
3     10011  HEAT/HOT WATER   194  100.0
4     10014  HEAT/HOT WATER   194  100.0
5     10016  HEAT/HOT WATER   107  100.0
6     10019  HEAT/HOT WATER   180  100.0
7     10023  HEAT/HOT WATER   150  100.0
8     10024  HEAT/HOT WATER   255  100.0
9     10025  HEAT/HOT WATER   557  100.0
10    10026  HEAT/HOT WATER   634  100.0
11    10027  HEAT/HOT WATER   666  100.0
12    10028  HEAT/HOT WATER   132  100.0
13    10029  HEAT/HOT WATER   588  100.0
14    10030  HEAT/HOT WATER   618  100.0
15    10031  HEAT/HOT WATER  1059  100.0
16    10032  HEAT/HOT WATER   986  100.0
17    10033  HEAT/HOT WATER   806  100.0
18    10034  HEAT/HOT WATER   671  100.0
19    10035  HEAT/HOT WATER   368  100.0
20    10036  HEAT/HOT WATER   121  100.0
21    10037  HEAT/HOT WATER   347  100.0
22    10039  HEAT/HOT WATER   680  100.0
23    10040  HEAT/HOT WATER   755  100.0
24    10128  HEAT/HOT WATER   138  100.0
25    10301  HEAT/HOT WATER   161  100.0
26    10451  HEAT/HOT WATER   817  100.0
27    10452  HEAT/HOT WATER  1382  100.0
28    10453  HEAT/HOT WATER  1245  100.0
29    10454  HEAT/HOT WATER   312  100.0

In [8]:
# ── Q6: Zillow price change 2020 to latest ────────────────────────
run("Q6: Zillow Home Value Change Since 2020 (Top 20)", """
    WITH first_last AS (
        SELECT zip_code,
               FIRST_VALUE(median_home_value) OVER (
                   PARTITION BY zip_code ORDER BY stat_month) AS price_start,
               LAST_VALUE(median_home_value) OVER (
                   PARTITION BY zip_code ORDER BY stat_month
                   ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS price_end
        FROM neighborhood_market_stat
    )
    SELECT zip_code,
           ROUND(price_start) AS price_2020,
           ROUND(price_end)   AS price_latest,
           ROUND(100.0 * (price_end - price_start) / NULLIF(price_start,0), 1) AS pct_change
    FROM first_last
    GROUP BY zip_code, price_start, price_end
    ORDER BY pct_change DESC
    LIMIT 20
""")

============================================================
  Q6: Zillow Home Value Change Since 2020 (Top 20)
============================================================
zip_code  price_2020  price_latest  pct_change
   11436    455497.0      690543.0        51.6
   11692    415784.0      615428.0        48.0
   11433    505996.0      721496.0        42.6
   10453    428253.0      594273.0        38.8
   11429    540370.0      741748.0        37.3
   10465    507851.0      690074.0        35.9
   11040    731968.0      992524.0        35.6
   10282   1581351.0     2137768.0        35.2
   11427    584509.0      784110.0        34.1
   11428    580394.0      776387.0        33.8
   10469    528743.0      707173.0        33.7
   11001    652250.0      869931.0        33.4
   10466    504688.0      670243.0        32.8
   10039    472399.0      626280.0        32.6
   11413    556271.0      733359.0        31.8
   10461    559274.0      734806.0        31.4
   10303    423969.0      556295.0        31.2
   11423    635276.0      832327.0        31.0
   11412    563670.0      738166.0        31.0
   10454    639611.0      834734.0        30.5

   zip_code  price_2020  price_latest  pct_change
0     11436    455497.0      690543.0        51.6
1     11692    415784.0      615428.0        48.0
2     11433    505996.0      721496.0        42.6
3     10453    428253.0      594273.0        38.8
4     11429    540370.0      741748.0        37.3
5     10465    507851.0      690074.0        35.9
6     11040    731968.0      992524.0        35.6
7     10282   1581351.0     2137768.0        35.2
8     11427    584509.0      784110.0        34.1
9     11428    580394.0      776387.0        33.8
10    10469    528743.0      707173.0        33.7
11    11001    652250.0      869931.0        33.4
12    10466    504688.0      670243.0        32.8
13    10039    472399.0      626280.0        32.6
14    11413    556271.0      733359.0        31.8
15    10461    559274.0      734806.0        31.4
16    10303    423969.0      556295.0        31.2
17    11423    635276.0      832327.0        31.0
18    11412    563670.0      738166.0        31.0
19    10454    639611.0      834734.0        30.5

In [9]:
# ── Q7: Avg price by property type ────────────────────────────────
run("Q7: Avg Sale Price by Property Type", """
    SELECT p.property_type,
           COUNT(*) AS num_sales,
           ROUND(AVG(st.sale_price)) AS avg_price,
           ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY st.sale_price)) AS median_price,
           ROUND(AVG(st.price_per_sqft)::numeric, 2) AS avg_price_per_sqft
    FROM property p
    JOIN sales_transaction st ON st.property_id = p.property_id
    WHERE p.property_type IS NOT NULL
    GROUP BY p.property_type
    ORDER BY avg_price DESC
""")

============================================================
  Q7: Avg Sale Price by Property Type
============================================================
property_type  num_sales  avg_price  median_price  avg_price_per_sqft
    APARTMENT       2605  3304821.0     1150000.0              536.77
        HOUSE      18970  1192321.0      905000.0              594.93
    TOWNHOUSE        617  1052810.0      695000.0                 NaN
        CONDO      82061   666595.0      259900.0                 NaN

  property_type  num_sales  avg_price  median_price  avg_price_per_sqft
0     APARTMENT       2605  3304821.0     1150000.0              536.77
1         HOUSE      18970  1192321.0      905000.0              594.93
2     TOWNHOUSE        617  1052810.0      695000.0                 NaN
3         CONDO      82061   666595.0      259900.0                 NaN

In [10]:
# ── Q8: Top 20 properties with biggest price appreciation ─────────
run("Q8: Top 20 Properties by Price Appreciation", """
    WITH multi_sale AS (
        SELECT property_id,
               MIN(sale_price) AS first_price,
               MAX(sale_price) AS last_price,
               COUNT(*)        AS num_sales
        FROM price_history
        GROUP BY property_id
        HAVING COUNT(*) >= 2
    )
    SELECT p.address, p.zip_code, b.borough_name,
           ms.first_price, ms.last_price,
           ROUND(ms.last_price - ms.first_price) AS price_gain,
           ROUND(100.0*(ms.last_price-ms.first_price)/NULLIF(ms.first_price,0),1) AS pct_gain
    FROM multi_sale ms
    JOIN property p ON p.property_id = ms.property_id
    JOIN borough b ON b.borough_id = p.borough_id
    ORDER BY pct_gain DESC
    LIMIT 20
""")

============================================================
  Q8: Top 20 Properties by Price Appreciation
============================================================
                    address zip_code  borough_name  first_price  last_price  price_gain  pct_gain
        9323 SHORE ROAD, 1H    11209      BROOKLYN     100000.0   6132440.0   6032440.0    6032.4
        9323 SHORE ROAD, 1H    11209      BROOKLYN     100000.0   6132440.0   6032440.0    6032.4
   212 WEST 93RD STREET, 7A    10025     MANHATTAN      56004.0   3200000.0   3143996.0    5613.9
   212 WEST 93RD STREET, 7A    10025     MANHATTAN      56004.0   3200000.0   3143996.0    5613.9
        N/A WATERFORD COURT    10305 STATEN ISLAND      53500.0   1474935.0   1421435.0    2656.9
        N/A WATERFORD COURT    10305 STATEN ISLAND      53500.0   1474935.0   1421435.0    2656.9
        510 PARK AVENUE, 9B    10022     MANHATTAN     127711.0   2850000.0   2722289.0    2131.6
        510 PARK AVENUE, 9B    10022     MANHATTAN     127711.0   2850000.0   2722289.0    2131.6
106 CENTRAL PARK SOUTH, 21M    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
106 CENTRAL PARK SOUTH, 21M    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
106 CENTRAL PARK SOUTH, 21O    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
106 CENTRAL PARK SOUTH, 21N    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
106 CENTRAL PARK SOUTH, 21N    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
106 CENTRAL PARK SOUTH, 21O    10019     MANHATTAN     997885.0  18896058.0  17898173.0    1793.6
       134-38 35 AVENUE, 3C    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9
       134-38 35 AVENUE, 3A    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9
       134-38 35 AVENUE, 3C    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9
       134-38 35 AVENUE, 3A    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9
       134-38 35 AVENUE, 3B    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9
       134-38 35 AVENUE, 3A    11354        QUEENS     399990.0   6911350.0   6511360.0    1627.9

,address,zip_code,borough_name,first_price,last_price,price_gain,pct_gain
0,"9323 SHORE ROAD, 1H",11209,BROOKLYN,100000.0,6132440.0,6032440.0,6032.4
1,"9323 SHORE ROAD, 1H",11209,BROOKLYN,100000.0,6132440.0,6032440.0,6032.4
2,"212 WEST 93RD STREET, 7A",10025,MANHATTAN,56004.0,3200000.0,3143996.0,5613.9
3,"212 WEST 93RD STREET, 7A",10025,MANHATTAN,56004.0,3200000.0,3143996.0,5613.9
4,N/A WATERFORD COURT,10305,STATEN ISLAND,53500.0,1474935.0,1421435.0,2656.9
5,N/A WATERFORD COURT,10305,STATEN ISLAND,53500.0,1474935.0,1421435.0,2656.9
6,"510 PARK AVENUE, 9B",10022,MANHATTAN,127711.0,2850000.0,2722289.0,2131.6
7,"510 PARK AVENUE, 9B",10022,MANHATTAN,127711.0,2850000.0,2722289.0,2131.6
8,"106 CENTRAL PARK SOUTH, 21M",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
9,"106 CENTRAL PARK SOUTH, 21M",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
10,"106 CENTRAL PARK SOUTH, 21O",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
11,"106 CENTRAL PARK SOUTH, 21N",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
12,"106 CENTRAL PARK SOUTH, 21N",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
13,"106 CENTRAL PARK SOUTH, 21O",10019,MANHATTAN,997885.0,18896058.0,17898173.0,1793.6
14,"134-38 35 AVENUE, 3C",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9
15,"134-38 35 AVENUE, 3A",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9
16,"134-38 35 AVENUE, 3C",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9
17,"134-38 35 AVENUE, 3A",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9
18,"134-38 35 AVENUE, 3B",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9
19,"134-38 35 AVENUE, 3A",11354,QUEENS,399990.0,6911350.0,6511360.0,1627.9

In [11]:
# ── Q9: Quality score tier vs avg sale price ──────────────────────
run("Q9: Neighborhood Quality Tier vs Avg Sale Price", """
    SELECT
        CASE
            WHEN quality_score >= 80 THEN 'High (80-100)'
            WHEN quality_score >= 60 THEN 'Medium (60-79)'
            ELSE 'Low (<60)'
        END AS quality_tier,
        COUNT(*) AS zip_count,
        ROUND(AVG(median_sale_price)) AS avg_sale_price,
        ROUND(AVG(violation_count)::numeric, 1) AS avg_violations,
        ROUND(AVG(complaint_count)::numeric, 1) AS avg_complaints
    FROM neighborhood_quality_score
    WHERE median_sale_price IS NOT NULL
    GROUP BY quality_tier
    ORDER BY avg_sale_price DESC
""")

============================================================
  Q9: Neighborhood Quality Tier vs Avg Sale Price
============================================================
  quality_tier  zip_count  avg_sale_price  avg_violations  avg_complaints
Medium (60-79)         28       2121037.0            48.1            54.3
     Low (<60)        114       1564618.0           422.7           419.5
 High (80-100)         41       1078810.0            10.2            15.8

     quality_tier  zip_count  avg_sale_price  avg_violations  avg_complaints
0  Medium (60-79)         28       2121037.0            48.1            54.3
1       Low (<60)        114       1564618.0           422.7           419.5
2   High (80-100)         41       1078810.0            10.2            15.8

In [12]:
# ── Q10: Annual sales volume and avg price by borough ─────────────
run("Q10: Annual Sales Trends by Borough (2020+)", """
    SELECT b.borough_name,
           EXTRACT(YEAR FROM st.sale_date)::int AS year,
           COUNT(*) AS num_sales,
           ROUND(AVG(st.sale_price)) AS avg_price
    FROM sales_transaction st
    JOIN property p ON p.property_id = st.property_id
    JOIN borough b ON b.borough_id = p.borough_id
    WHERE st.sale_date IS NOT NULL
      AND EXTRACT(YEAR FROM st.sale_date) >= 2020
    GROUP BY b.borough_name, year
    ORDER BY b.borough_name, year
""")

print("\n" + "="*60)
print("  All 10 analytical queries complete.")
print("="*60)

============================================================
  Q10: Annual Sales Trends by Borough (2020+)
============================================================
 borough_name  year  num_sales  avg_price
        BRONX  2025       1925  1313048.0
        BRONX  2026       1639   753388.0
     BROOKLYN  2025       6194  1469332.0
     BROOKLYN  2026       5366  1526629.0
  CONNECTICUT  2020         41   224444.0
    MANHATTAN  2025       6574  3084086.0
    MANHATTAN  2026       5786  2596301.0
       QUEENS  2025       7454   824484.0
       QUEENS  2026       6225   832000.0
STATEN ISLAND  2025       2420   799935.0
STATEN ISLAND  2026       1602   767320.0

============================================================
  All 10 analytical queries complete.
============================================================